#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
AIRFLOW_ENV_FILE="$ROOT_DIR/airflow/.env"

required_vars=(
  FRAUD_GCP_PROJECT_ID
  GCP_GCS_BUCKET
  FRAUD_BQ_DATASET
  DATAFORM_REPOSITORY_ID
  DATAFORM_RUN_WORKFLOW_CONFIG_ID
  DATAFORM_ASSERT_WORKFLOW_CONFIG_ID
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "[airflow-env] Missing required environment variable: ${var_name}" >&2
    echo "[airflow-env] Export step 6.1 variables first, then rerun this script." >&2
    exit 1
  fi
done

cat > "$AIRFLOW_ENV_FILE" <<EOF
FRAUD_PROJECT_ROOT=/opt/project
GOOGLE_APPLICATION_CREDENTIALS=/opt/project/infra/terraform/keys/terraform-sa-key.json

FRAUD_GCP_PROJECT_ID=${FRAUD_GCP_PROJECT_ID}
GCP_REGION=${GCP_REGION:-us-central1}
GCP_GCS_BUCKET=${GCP_GCS_BUCKET}
GCP_DATAPROC_DEPS_BUCKET=${GCP_DATAPROC_DEPS_BUCKET:-${GCP_GCS_BUCKET}}
GCP_DATAPROC_SERVICE_ACCOUNT=${GCP_DATAPROC_SERVICE_ACCOUNT:-}
GCP_DATAPROC_SUBNET=${GCP_DATAPROC_SUBNET:-}
GCP_DATAPROC_SPARK_PROPERTIES=${GCP_DATAPROC_SPARK_PROPERTIES:-spark.dynamicAllocation.enabled=false,spark.driver.cores=4,spark.executor.instances=2,spark.executor.cores=4}

FRAUD_SILVER_PATH=${FRAUD_SILVER_PATH:-gs://${GCP_GCS_BUCKET}/lake/silver/scored_transactions}
FRAUD_HOURLY_OUTPUT_BASE=${FRAUD_HOURLY_OUTPUT_BASE:-gs://${GCP_GCS_BUCKET}/lake/gold/hourly_batch}
FRAUD_MODEL_OUTPUT=${FRAUD_MODEL_OUTPUT:-gs://${GCP_GCS_BUCKET}/ml/artifacts/fraud_rf_pipeline}
FRAUD_LABELS_CSV=${FRAUD_LABELS_CSV:-gs://${GCP_GCS_BUCKET}/inputs/transaction_log.csv}

FRAUD_BQ_DATASET=${FRAUD_BQ_DATASET}
FRAUD_RETRAINING_TABLE=${FRAUD_RETRAINING_TABLE:-retraining_dataset}
FRAUD_BQ_TEMP_BUCKET=${FRAUD_BQ_TEMP_BUCKET:-${GCP_GCS_BUCKET}}

DATAFORM_REGION=${DATAFORM_REGION:-${GCP_REGION:-us-central1}}
DATAFORM_REPOSITORY_ID=${DATAFORM_REPOSITORY_ID}
DATAFORM_RUN_WORKFLOW_CONFIG_ID=${DATAFORM_RUN_WORKFLOW_CONFIG_ID}
DATAFORM_ASSERT_WORKFLOW_CONFIG_ID=${DATAFORM_ASSERT_WORKFLOW_CONFIG_ID}

FRAUD_HOURLY_BATCH_PY_URI=${FRAUD_HOURLY_BATCH_PY_URI:-gs://${GCP_GCS_BUCKET}/code/batch/hourly_batch_processing.py}
FRAUD_HOURLY_BQ_LOAD_PY_URI=${FRAUD_HOURLY_BQ_LOAD_PY_URI:-gs://${GCP_GCS_BUCKET}/code/batch/load_hourly_batch_to_bigquery.py}
FRAUD_DAILY_MODEL_REFRESH_PY_URI=${FRAUD_DAILY_MODEL_REFRESH_PY_URI:-gs://${GCP_GCS_BUCKET}/code/batch/daily_model_refresh.py}

FRAUD_ALERT_EMAILS=${FRAUD_ALERT_EMAILS:-}

AIRFLOW__SMTP__SMTP_HOST=${AIRFLOW__SMTP__SMTP_HOST:-}
AIRFLOW__SMTP__SMTP_PORT=${AIRFLOW__SMTP__SMTP_PORT:-587}
AIRFLOW__SMTP__SMTP_STARTTLS=${AIRFLOW__SMTP__SMTP_STARTTLS:-True}
AIRFLOW__SMTP__SMTP_SSL=${AIRFLOW__SMTP__SMTP_SSL:-False}
AIRFLOW__SMTP__SMTP_USER=${AIRFLOW__SMTP__SMTP_USER:-}
AIRFLOW__SMTP__SMTP_PASSWORD=${AIRFLOW__SMTP__SMTP_PASSWORD:-}
AIRFLOW__SMTP__SMTP_MAIL_FROM=${AIRFLOW__SMTP__SMTP_MAIL_FROM:-}
EOF

echo "[airflow-env] Wrote $AIRFLOW_ENV_FILE"
echo "[airflow-env] Preview:"
grep -E 'FRAUD_GCP_PROJECT_ID|FRAUD_SILVER_PATH|FRAUD_HOURLY_OUTPUT_BASE|FRAUD_MODEL_OUTPUT|FRAUD_BQ_DATASET|FRAUD_RETRAINING_TABLE|DATAFORM_REPOSITORY_ID' "$AIRFLOW_ENV_FILE"
